services:
  redis:
    image: "redis:6.2.6-alpine"

  erdbeere:
    build:
      context: ./../..
      dockerfile: docker/development/Dockerfile
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    ports:
      - "3005:3000"
    container_name: erdbeere
    depends_on:
      - redis


